In [1]:
import numpy as np

In [21]:
displacement = 307.0
horsepower = 130.0
weight = 3504.0
acceleration = 12.0
cylinders = 8
origin = 1

## if cylinders = 9, origin = 1 -> onehot encoding
import numpy as np
if cylinders == 3:
  cylinder = np.array([1,0,0,0,0])
elif cylinders == 4:
  cylinder = np.array([0,1,0,0,0])
elif cylinders == 5:
  cylinder = np.array([0,0,1,0,0])
elif cylinders == 6:
  cylinder = np.array([0,0,0,1,0])
else :  # 8
  cylinder = np.array([0,0,0,0,1])

x_continues = np.array([displacement, horsepower, weight, acceleration])
# cylinders = np.array([0,0,0,0,1])  # 8
origin = np.array([1,0,0])  # 1

In [9]:
type(x_continues), type(cylinders), type(origin)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [13]:
# np.concatenate((a, b), axis=None)
result = np.concatenate((x_continues, cylinders, origin), axis=None)
result, result.shape

((12,),
 array([3.070e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]))

In [24]:
# result.reshape(1, 12)
result = result.reshape(-1, result.size)
result, result.shape, result.size

(array([[3.070e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
         0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]]),
 (1, 12),
 12)

In [22]:
result

array([[3.070e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]])

## function 이해

In [26]:
21 + 14

35

In [27]:
32 + 45

77

In [50]:
# f01 = 32
# s02 = 21
def sum(f01, s02):
  first = s02 
  second = f01
  result = first + second
  return result, second, first

In [52]:
_, r02, r03 = sum(21, 564)  # 언더바(_)도 변수로 사용 가능
print(r01, r02)

585 21


In [1]:
# def differenceVars(*var01, **args02)
def diffparam(*var_list, **var_dict):
  print(var_dict)
  result01 = len(var_list)
  return result01

In [2]:
diffparam(1,2,3, a=2, b=3)

{'a': 2, 'b': 3}


3

In [3]:
diffparam(1,2,3,5,6, c=5, d=6, a=2, b=3)

{'c': 5, 'd': 6, 'a': 2, 'b': 3}


5